### ISSUE TITLE
Hacktoberfest 2019

### ISSUE THREAD

**Issue by grikomsn** [SurabayaJS/events#1]
'tis the month of Hacktoberfest 2019. Do improve and fix some things and send your pull requests. 👋🏻

**Comment by Crammers** [comment]
Hi Ive submitted a PR to update the .gitignore and include .DS_Store but it failed checks by the Now bot. Not sure what the issue is. Is there something I can do and resubmit?

**Comment by grikomsn** [comment]
> Hi Ive submitted a PR to update the .gitignore and include .DS_Store but it failed checks by the Now bot. Not sure what the issue is. Is there something I can do and resubmit?

Hello there,

It is not failing but requires approval since the API needs internal credentials to build. Not to mention your PR is just updating `.gitignore`. 😅

![image](https://user-images.githubusercontent.com/8220954/66270868-633f5c00-e882-11e9-8545-cd9117f3de40.png)
